package info.inpn.INPNMod;
import net.minecraftforge.fml.common.ModMetadata;

public class Modinfo {

		public static void loadInfo(ModMetadata meta) {
			meta.modId = INPNMod.MODID;
			meta.name = INPNMod.MODNAME;
			meta.description ="大日本ペイント帝國海軍運營 #ホモの惑星サーバー 専用MOD";
			meta.version = "0.0.0" ;
			meta.url = "https://minecraft.inpn.info";
			meta.authorList.clear();
			meta.authorList.add("たまご");
			meta.authorList.add("名有り");
			meta.credits = "たまご@INPN_Officer,名有り@_naari_";
			meta.logoFile ="https://minecraft.inpn.info/img/ico.ico";
			meta.autogenerated = false;
		}

}
